version: "3.8"
services:
  app:
    build: .
    ports:
      - "4200:4200"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      
    command: npm start -- --host 0.0.0.0 --poll 500
